on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/cli_test.yml'
      - 'packages/jaspr/**'
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/cli_test.yml'
      - 'packages/jaspr/**'

name: CLI Test

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: CLI Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3
      - uses: bluefireteam/melos-action@v1
      
      - name: Run tests
        run: melos run test
